title: Santhosh Kumari Kage
logo: /assets/img/logo.jpeg
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://github.com/skkage">GitHub</a>
theme: jekyll-theme-minimal
